# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0d12b4b906a1f7fa5e03189a2b9e3cf7"
name = "wishlist"
handle = "wishlist-409"
application_url = "https://citation-adaptor-replication-tr.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hydrogen-starter.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://citation-adaptor-replication-tr.trycloudflare.com/auth/callback",
  "https://citation-adaptor-replication-tr.trycloudflare.com/auth/shopify/callback",
  "https://citation-adaptor-replication-tr.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
